function [states] = statesList
  states{1+ 0} = struct(...
    'type', 'pose',...
    'range', [1; 2; 3],...
    'value', [0; 0; d2r(10)]);

  states{1+ 1} = struct(...
    'type', 'pose',...
    'range', [4; 5; 6],...
    'value', [1; 0.05; d2r(-10)]);

  states{1+ 2} = struct(...
    'type', 'pose',...
    'range', [7; 8; 9],...
    'value', [2; -0.25; d2r(-20)]);

  states{1+ 3} = struct(...
    'type', 'lmk',...
    'range', [10; 11],...
    'value', [0.9, 0.8]);

  states{1+ 4} = struct(...
    'type', 'lmk',...
    'range', [12; 13],...
    'value', [2.2, 0.6]);

  states{1+ 5} = struct(...
    'type', 'lmk',...
    'range', [14; 15],...
    'value', [1.6, -0.75]);

  states{1+ 6} = struct(...
    'type', 'lmk',...
    'range', [16; 17],...
    'value', [2.3, -1]);
end
